name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: instasergio/rmc-exporter:latest
      - 
        name: Deploy on Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.DEPLOY_WEBHOOK }}'
          method: 'GET'
      -
        uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.KEY_JSON }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          DOCKERFILE_PATH: .
          IMAGE_NAME: rmc-exporter
          IMAGE_TAG: latest
