name: Ya Cloud push and deploy

on: workflow_dispatch

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      -
        name: Pull, tag, and push image to Yandex Cloud Container Registry
        env: 
          CR_REGISTRY: ${{ secrets.REGISTRY_ID }}
          CR_REPOSITORY: rmc-exporter
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull instasergio/rmc-exporter:latest
          docker tag instasergio/rmc-exporter:latest cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
      - 
        name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: rmc-exporter
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          public: true
          revision-env: ${{ secrets.YC_ENV }}
          revision-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          revision-image-url: cr.yandex/${{ secrets.REGISTRY_ID }}/rmc-exporter:${{ github.sha }}
